version: "3.8"

services:
  db:
    image: postgres
    environment:
      POSTGRES_DB: productdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - dbdata:/var/lib/postgresql/data

  app:
    build:
      ports:
        - "8080:8080"
      depends_on:
        - db

volumes:
  dbdata: